name: skindetectionapplication
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  tabler_icons_flutter: ^2.11.0
  flutter_svg: ^2.0.17
  flutter_launcher_icons: ^0.14.3
  firebase_core: ^2.30.1
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.17.5
  permission_handler: ^12.0.0+1
  camera: ^0.10.5+2
  gal: ^2.3.1
  vector_math: ^2.1.0
  image_picker: ^0.8.5+3
  # latlong2: ^0.9.1
  flutter_map: ^7.0.2
  geolocator: ^12.0.0
  dot_navigation_bar: ^1.0.2
  firebase_database: ^10.5.7
  tflite_flutter: ^0.11.0
  shared_preferences: 2.3.3
  path: ^1.6.1
  google_maps_flutter: ^2.10.1
  rename: ^3.0.2
  # flutter_google_maps_webservices: ^1.1.1 
  # location: ^8.0.0 
  google_places_flutter: ^2.1.0
  intl: 0.19.0
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.7+1
  firebase_storage: ^11.7.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: ^0.14.3  
  flutter_lints: ^4.0.0
  
    
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/DERMEX_AI.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  
  


flutter:
  uses-material-design: true
  assets:
   - assets/map_style.json
   - assets/image/
   - assets/image/hospital.png
  #  - assets/image/DERMEX_AI.jpg
  #  - assets/model.tflite
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
