// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAudts_Gj2-llvB57k3mdA2uhdB1blf26Y',
    appId: '1:215624511479:web:45ec87ae3ff97883f2c8f2',
    messagingSenderId: '215624511479',
    projectId: 'hospital-89ea3',
    authDomain: 'hospital-89ea3.firebaseapp.com',
    storageBucket: 'hospital-89ea3.firebasestorage.app',
    measurementId: 'G-99Z5DQ45SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9EPgPpsEI8W2zab5mF--Bm8RFFbSHAG8',
    appId: '1:215624511479:android:f0294507e572929cf2c8f2',
    messagingSenderId: '215624511479',
    projectId: 'hospital-89ea3',
    storageBucket: 'hospital-89ea3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3uCTYdokh5l-KnpHQFnAwogGqPOaDpVs',
    appId: '1:215624511479:ios:1f22688cb66215f8f2c8f2',
    messagingSenderId: '215624511479',
    projectId: 'hospital-89ea3',
    storageBucket: 'hospital-89ea3.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );
}
